name: job_scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - brotlipy=0.7.0
  - bs4=4.12.2
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - idna=3.4
  - ipykernel=6.15.0
  - ipython=8.13.2
  - jedi=0.18.2
  - jupyter_client=7.0.6
  - jupyter_core=5.3.0
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21=
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numpy=1.24.3
  - openssl=3.1.0
  - packaging=23.1
  - pandas=2.0.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=3.5.1
  - prompt-toolkit=3.0.38
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3
  - pyzmq=19.0.2
  - readline=8.2
  - requests=2.29.0
  - setuptools=66.0.0
  - six=1.16.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - geosky==1.0.9
